### ISSUE TITLE
Consider renaming bindCompose to composedViewFactory

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin-compose#19]
The term `composed` is consistent with the Compose `composed` function to build Modifiers as composable functions, and also with the `Workflow.composed` builder function for `ComposeWorkflow` (which was so-named to be consistent with the modifier builder as well).

The name `bindCompose`, in particular the term "bind", is vestigial from when `ViewFactory` was called `ViewBinding`, so using "ViewFactory" in the name instead seems more logical. That said, I don't feel too strongly since the function is still conceptually "binding" the composable lambda to a particular rendering type.

Thoughts?

**Comment by digitalbuddha** [comment]
View factory feels more logical. It is how I describe something that takes a rendering and returns a view
